///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SpeedTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SpeedTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("f576162f-f336-45e8-b069-ccfbe6b9efbc")]
    public partial class SpeedTestsRepository : RepoGenBaseFolder
    {
        static SpeedTestsRepository instance = new SpeedTestsRepository();
        SpeedTestsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        SpeedTestsRepositoryFolders.OpenSnapXRoutineAppFolder _opensnapxroutine;

        /// <summary>
        /// Gets the singleton class instance representing the SpeedTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("f576162f-f336-45e8-b069-ccfbe6b9efbc")]
        public static SpeedTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SpeedTestsRepository() 
            : base("SpeedTestsRepository", "/", null, 0, false, "f576162f-f336-45e8-b069-ccfbe6b9efbc", ".\\RepositoryImages\\SpeedTestsRepositoryf576162f.rximgres")
        {
            _snapxuntitled = new SpeedTestsRepositoryFolders.SnapXUntitledAppFolder(this);
            _opensnapxroutine = new SpeedTestsRepositoryFolders.OpenSnapXRoutineAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f576162f-f336-45e8-b069-ccfbe6b9efbc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
        public virtual SpeedTestsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The OpenSnapXRoutine folder.
        /// </summary>
        [RepositoryFolder("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
        public virtual SpeedTestsRepositoryFolders.OpenSnapXRoutineAppFolder OpenSnapXRoutine
        {
            get { return _opensnapxroutine; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class SpeedTestsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _remeasureInfo;
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "fba33c25-8c4b-40d7-9138-93af7c3ad7b6", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "db7aafa7-e18d-40aa-8b9f-4beccd9956b0");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container/form//button[@text='&OK']", 30000, null, "f7b05518-65b8-4d1a-b3d0-ef4b40182a53");
                _remeasureInfo = new RepoItemInfo(this, "ReMeasure", "container/form/?/?/element/element/container/button[@text='Re-Measure' and @accessiblestate='Focusable']", 30000, null, "fdde19aa-2930-49b2-b57f-e7ed19b7f556");
                _finishInfo = new RepoItemInfo(this, "Finish", "container/form/?/?/element/element/container/button[@text='Finish' and @accessiblestate='Default, Focusable']", 30000, null, "5274fe14-9b92-4e07-9dbc-ece5afef7527");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("db7aafa7-e18d-40aa-8b9f-4beccd9956b0")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("db7aafa7-e18d-40aa-8b9f-4beccd9956b0")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("f7b05518-65b8-4d1a-b3d0-ef4b40182a53")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("f7b05518-65b8-4d1a-b3d0-ef4b40182a53")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ReMeasure item.
            /// </summary>
            [RepositoryItem("fdde19aa-2930-49b2-b57f-e7ed19b7f556")]
            public virtual Ranorex.Button ReMeasure
            {
                get
                {
                    return _remeasureInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReMeasure item info.
            /// </summary>
            [RepositoryItemInfo("fdde19aa-2930-49b2-b57f-e7ed19b7f556")]
            public virtual RepoItemInfo ReMeasureInfo
            {
                get
                {
                    return _remeasureInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("5274fe14-9b92-4e07-9dbc-ece5afef7527")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("5274fe14-9b92-4e07-9dbc-ece5afef7527")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

        /// <summary>
        /// The OpenSnapXRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
        public partial class OpenSnapXRoutineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filenamefieldInfo;

            /// <summary>
            /// Creates a new OpenSnapXRoutine  folder.
            /// </summary>
            public OpenSnapXRoutineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenSnapXRoutine", "/form[@title='Open Snap-X Routine']", parentFolder, 30000, null, true, "1b207ee9-47bc-4776-9e09-babd5b1318ab", "")
            {
                _filenamefieldInfo = new RepoItemInfo(this, "FileNameField", "?/?/text[@controlid='1148']", 30000, null, "4ffde906-5caa-4e1f-9916-cde343dfc1a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileNameField item.
            /// </summary>
            [RepositoryItem("4ffde906-5caa-4e1f-9916-cde343dfc1a1")]
            public virtual Ranorex.Text FileNameField
            {
                get
                {
                    return _filenamefieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FileNameField item info.
            /// </summary>
            [RepositoryItemInfo("4ffde906-5caa-4e1f-9916-cde343dfc1a1")]
            public virtual RepoItemInfo FileNameFieldInfo
            {
                get
                {
                    return _filenamefieldInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}